#!/bin/bash
set -e

echo "=== Generating lib/config/env.dart from environment variables ==="
mkdir -p lib/config
cat > lib/config/env.dart << EOF
// Auto-generated by cloudflare-build.sh — DO NOT COMMIT
class Env {
  static const String workerBaseUrl = '${WORKER_BASE_URL}';
}
EOF

echo "=== flutter pub get ==="
flutter pub get

echo "=== flutter build web --release ==="
flutter build web --release
